CC = g++

CFLAGS = -c -Wall -Wsign-compare

LDFLAGS = -lfltk -lXext -lX11 -lm

SOURCES = main.cpp 

OBJECTS = $(SOURCES:.cpp=.o)

EXECUTABLE = run

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@ $(LDFLAGS)

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf *.o $(EXECUTABLE)